name: Release

on:
  pull_request:
    branches:
      - main

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        run: |
          echo "PR元のブランチ: ${{ github.head_ref }}"
          if [ "{{ github.head_ref }}" != "stg" ]; then
            echo "PR元のブランチがstgではありません"
            exit 1
          fi
